repos:
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
    -   id: clang-format
        files: ^src/
        exclude: 'lib/'
    -   id: cpplint
        files: ^src/
        exclude: 'lib/'
    -   id: cppcheck
        args: [--force]
        files: ^src/
        exclude: 'lib/'
